---
title: "Hipotese 1"
output:
  pdf_document: default
  html_notebook: default
---
```{r}
library(tidyverse)
library(ggpubr)
library(rstatix)
source("utils.R")
```
# Hipotese 1

u1 = AVG(SRTF(tat_per_cpu))
u2 = AVG(FCFS(tat_per_cpu))

H0: u1 = u2
H1: u1 < u2

#Load data

```{r}
wk = load_workload("h1",all_seeds = TRUE)
wk$scheduler = as.factor(wk$scheduler)
wk$workload = as.factor(wk$workload)
wk = select(wk,scheduler,seed,tat_per_cpu)
```

#Agrupar os dados
```{r}
wka = aggregate(. ~scheduler+seed,data=wk,mean,na.rm=TRUE)
srtf = wka[wka$scheduler=="SRTF",]
fcfs = wka[wka$scheduler=="FCFS",]
```


# Testar normalidade
Para n>30, pelo TLC podemos assumir normalidade.
Caso contrário, podemos testar com, por exemplo, o Shapiro-test

```{r}
shapiro.test(fcfs$tat_per_cpu)
shapiro.test(srtf$tat_per_cpu)

ggqqplot(fcfs$tat_per_cpu)
ggqqplot(srtf$tat_per_cpu)
```


#Paired T-test

```{r}
t.test(
  srtf$tat_per_cpu, fcfs$tat_per_cpu, paired = TRUE, alternative = "less"
)
```
```{r}
gen_density_by_scheduler(wk,"tat_per_cpu")
```


# Hipotese 1.1

Achamos que não vai haver diferença significativa entre SJF e SRTF, mesmo um sendo preenptive e o outro não

u1 = AVG(SRTF(ready_wait_time/nbursts))
u2 = AVG(SJF(ready_wait_time/nbursts))

H0: u1 = u2
H1: u1 != u2


```{r}
sjf = wka[wka$scheduler=="SJF",]
shapiro.test(sjf$tat_per_cpu)
t.test(
  srtf$tat_per_cpu, sjf$tat_per_cpu, paired = TRUE
)

wk = load_workload("h1",all_seeds=TRUE)

# wk %>%
# pairwise_t_test(
#   tat_per_cpu ~ scheduler, paired = TRUE, p.adjust.method = "bonferroni"
# )
```

```{r}

```

